version: '3'
services:
  lr-eth:
    image: node:11
    container_name: truffle-issue-repro
    volumes:
      - .:/usr/src/app:cached
    entrypoint: |
      bash -c "cd /usr/src/app && \
      npm install -g --unsafe-perm truffle@5.0.26 && \
      npm install && \
      rm -rf build/contracts/* && \
      npm run migrate-goerli && \
      echo 'DEPLOYMENT FINISHED SUCCESSFULLY'"
